<a href="https://colab.research.google.com/github/SamudralaAjaykumarrr/ai-security-portfolio/blob/main/Day2_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("Using device:", "cuda" if torch.cuda.is_available() else "cpu")


PyTorch version: 2.8.0+cu126
Using device: cpu


In [2]:
x = torch.tensor([1, 2, 3, 4, 5])
print("x:", x)

y = torch.zeros(2, 3)
print("y (zeros):\n", y)

z = torch.rand(2, 3)
print("z (random):\n", z)


x: tensor([1, 2, 3, 4, 5])
y (zeros):
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
z (random):
 tensor([[0.4356, 0.0211, 0.6228],
        [0.7622, 0.6078, 0.8964]])


In [3]:
print("x + 10:", x + 10)
print("x * 2:", x * 2)
print("x * [5,4,3,2,1]:", x * torch.tensor([5,4,3,2,1]))


x + 10: tensor([11, 12, 13, 14, 15])
x * 2: tensor([ 2,  4,  6,  8, 10])
x * [5,4,3,2,1]: tensor([5, 8, 9, 8, 5])


In [4]:
x_reshaped = x.view(5, 1)
print("Reshaped x:\n", x_reshaped)


Reshaped x:
 tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x_gpu = x.to(device)
print("Tensor on device:", x_gpu)


Tensor on device: tensor([1, 2, 3, 4, 5])
